import * as React from "react";
import { cn } from "@nucleux/utils";
import { Sparkles, Info } from "lucide-react";

export type AiDisclosureVariant = "pill" | "badge" | "banner";

export interface AiDisclosureProps extends React.HTMLAttributes<HTMLDivElement> {
  /** Presentation: inline `pill`, corner `badge`, or full-width `banner`. */
  variant?: AiDisclosureVariant;
  /** Leading icon. Defaults to a sparkle. */
  icon?: React.ReactNode;
  /** Label / message. Ignored if `children` is provided. Has a per-variant default. */
  label?: React.ReactNode;
}

const defaults: Record<AiDisclosureVariant, string> = {
  pill: "AI-assisted",
  badge: "Made with AI",
  banner: "This content was generated by AI. Review it before relying on it.",
};

/**
 * A provenance marker that content was authored or assisted by AI — an
 * anti-deception trust signal, as an inline pill, corner badge, or banner.
 * Source: Figma "Trust & Disclosure / AI disclosure".
 */
export const AiDisclosure = React.forwardRef<HTMLDivElement, AiDisclosureProps>(
  ({ variant = "pill", icon, label, className, children, ...props }, ref) => {
    const content = children ?? label ?? defaults[variant];
    const glyph = icon ?? <Sparkles aria-hidden="true" />;
    if (variant === "banner") {
      return (
        <div
          ref={ref}
          className={cn(
            "flex items-center gap-2 rounded-lg border border-brand/20 bg-brand-muted/40 px-3 py-2 text-sm text-foreground [&_svg]:size-4 [&_svg]:text-brand",
            className,
          )}
          {...props}
        >
          {glyph}
          <span>{content}</span>
        </div>
      );
    }
    return (
      <div
        ref={ref}
        className={cn(
          "inline-flex w-fit items-center gap-1 rounded-full font-medium text-brand [&_svg]:size-3.5",
          variant === "badge"
            ? "bg-background/90 px-2 py-1 text-xs shadow-sm backdrop-blur"
            : "bg-brand-muted/60 px-2.5 py-1 text-xs",
          className,
        )}
        {...props}
      >
        {glyph}
        <span>{content}</span>
      </div>
    );
  },
);
AiDisclosure.displayName = "AiDisclosure";

export interface AiCaveatProps extends React.HTMLAttributes<HTMLParagraphElement> {
  /** Leading icon. Defaults to an info glyph. Pass `null` to omit. */
  icon?: React.ReactNode;
}

/**
 * A short fallibility disclaimer shown near AI output — the standard
 * "verify before you trust" caption.
 * Source: Figma "Onboarding / Caveat".
 */
export const AiCaveat = React.forwardRef<HTMLParagraphElement, AiCaveatProps>(
  ({ icon, className, children, ...props }, ref) => (
    <p
      ref={ref}
      className={cn(
        "inline-flex items-center gap-1.5 text-xs text-muted-foreground [&_svg]:size-3.5",
        className,
      )}
      {...props}
    >
      {icon === undefined ? <Info aria-hidden="true" /> : icon}
      <span>{children ?? "AI can make mistakes. Verify important information."}</span>
    </p>
  ),
);
AiCaveat.displayName = "AiCaveat";
