import type { Meta, StoryObj } from "@storybook/react";
import { Alert } from "./alert";

const meta = {
  title: "Primitives/Alert",
  component: Alert,
  tags: ["autodocs"],
  parameters: { layout: "padded" },
  args: {
    variant: "default",
    children:
      "This content has been automatically generated by AI and is intended for informational purposes.",
  },
  decorators: [
    (Story) => (
      <div className="mx-auto max-w-xl">
        <Story />
      </div>
    ),
  ],
} satisfies Meta<typeof Alert>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {};
export const WithTitle: Story = {
  args: { variant: "info", title: "Heads up", children: "You can theme every alert via tokens." },
};

export const Variants: Story = {
  render: () => (
    <div className="space-y-3">
      <Alert variant="info" title="Information">Neutral, low-urgency context.</Alert>
      <Alert variant="success" title="Saved">Your changes were saved.</Alert>
      <Alert variant="warning" title="Careful">This action affects billing.</Alert>
      <Alert variant="destructive" title="Something went wrong">Could not reach the server.</Alert>
    </div>
  ),
};
